In [1]:
import sys
sys.path.append('../')

from Utils.Imports import *
import tensorflow as tf

from Losses.BruteForceChamfer import BruteForceChamfer
from Losses.BruteForceChamferTF import BruteForceChamferTF

In [5]:
# torch vs tensorflow chamfer distance unit test

num_point1 = 5
num_point2 = 3
num_features = 4
np.random.seed(1)
array1 = np.random.randint(0, high=4, size=(num_point1, num_features))
array2 = np.random.randint(0, high=4, size=(num_point2, num_features))
print('array1 =')
print(array1)
print('array2 =')
print(array2)
print()

array1_pt = torch.from_numpy(array1).float()
array2_pt = torch.from_numpy(array2).float()
dist1, dist2, idx1, idx2 = BruteForceChamfer(array1_pt, array2_pt)
print(dist1) 
print(dist2) 
print(idx1) 
print(idx2)
print()

array1_tf = tf.constant(array1, dtype=tf.float64)
array2_tf = tf.constant(array2, dtype=tf.float64)
dist1, dist2, idx1, idx2 = BruteForceChamferTF(array1_tf, array2_tf)

with tf.Session() as sess:
    print(sess.run(dist1))
    print(sess.run(dist2))
    print(sess.run(idx1))
    print(sess.run(idx2))

array1 =
[[1 3 0 0]
 [3 1 3 1]
 [3 0 0 1]
 [0 3 1 0]
 [2 1 2 0]]
array2 =
[[2 1 2 0]
 [3 0 2 0]
 [1 2 2 0]]

tensor([0.0000, 1.4142, 1.4142])
tensor([2.2361, 1.7321, 2.2361, 1.7321, 0.0000])
tensor([4, 4, 4])
tensor([2, 1, 1, 2, 0])

[0.         1.41421356 1.41421356]
[2.23606798 1.73205081 2.23606798 1.73205081 0.        ]
[4 4 4]
[2 0 1 2 0]
